### DISCUSSION TITLE
TC Config using regex

### DISCUSSION THREAD

**Discussion by junukwon7** [hydro-dev/Hydro#44] [Q&A] [answered]
I was trying to use RegEx but couldn't make it.
I have 100 data and each one is named #.in and #.out

Below is what I wanted but didn't work.
```
type: default
score: 100
time: 1s
memory: 256m
cases:
  - input: /^([a-zA-Z]*)([0-9]+).in$/
    output: /^([a-zA-Z]*)([0-9]+).out$/
```
I would really appreciate it if you help me.
