### ISSUE TITLE
更简洁的 config.yaml

### ISSUE THREAD

**Issue by Macesuted** [hydro-dev/Hydro#111]
![image](https://user-images.githubusercontent.com/57275149/115801510-85baab00-a40f-11eb-8530-47a8aaa313f0.png)

当题目有 Subtask 等需要的时候，需要在 config.yaml 里面写入所有文件的名称，在文件多或文件名长的时候可能会显得相当繁琐。

希望能够像 SYZOJ 那样，能在文件开头设置所有文件名的大体结构，再在下方写入文件的不同部分。或是像 UOJ 那样可以在设置文件开头说明所有文件的共同前缀后缀。

**Comment by Macesuted** [comment]
或者说允许 `input` 和 `output` 后方的文件名中使用正则表达式或是通配符之类的也可以。

**Comment by undefined-moe** [comment]
在新版本后以上配置等同于

```yaml
subtasks:
- score: 15
  id: 1
- score: 5
  id: 2
```
