### ISSUE TITLE
提交答案题支持 Special Judge

### ISSUE THREAD

**Issue by Macesuted** [hydro-dev/Hydro#112]

**Comment by undefined-moe** [comment]
请详细描述该功能的应用场景。

以下为可行的替代方案：

langs.yaml

```yaml
plain:
  type: interpreter
  code_file: foo
  execute: /bin/cat ${dir}/foo
```

并使用default判题逻辑。
