### ISSUE TITLE
请问hydro题目是否支持自定义语言（即自己写一个编译脚本）？

### ISSUE THREAD

**Issue by segment-tree** [hydro-dev/Hydro#171]
比如说在选手提交的代码后面插入一段代码再编译。

```sh
echo | cat extra_file.cpp >> foo.cc
g++ foo.cc -o code
```

![](https://cdn.luogu.com.cn/upload/image_hosting/v165dwli.png)

这里写了支持，但我不知道config.yaml怎么书写。

**Comment by undefined-moe** [comment]
```ts
type template = Record<string, [string, string]>;
```

e.g.

```yaml
template:
  cc:
    - |
      #include<iostream>
      using namespace std;
      int main() {
    - |
      return 0;
      }
```

cc为系统设置中对应编译选项的语言ID。
配置该项后，不在模板列表中的程序将无法提交。
