### ISSUE TITLE
Subtask dependencies?

### ISSUE THREAD

**Issue by junukwon7** [hydro-dev/Hydro#35]
Can the admin can set dependencies? This prevents getting accept in bigger subtasks while getting wrong in small ones.

i.e. Regular expressions used in cms-dev(IOI site)
sub1(30pts), sub2(30pts), sub3(30pts) and sub1, sub2 ⊂ sub3
```
[ [30, "sub1_"], [30, "sub2_"], [40, "sub1_|sub2_|sub3_"] ]
```

**Comment by undefined-moe** [comment]
I can't understand what it means. does it mean when only run subtask3 when subtask1 and subtask2 are passed?

**Comment by junukwon7** [comment]
> I can't understand what it means. does it mean when only run subtask3 when subtask1 and subtask2 are passed?

In example, subtask 1 has limitation N<=10, and sub2 has N<=100.
This means that sub1 ⊂ sub2. But there might be submissions that get accepted only in sub2. (which means data for sub2 is weak.) However, it is clear that the submission is wrong so it should get 0 points.

**Comment by junukwon7** [comment]
> I can't understand what it means. does it mean when only run subtask3 when subtask1 and subtask2 are passed?

If the configuration is:
```
subtasks:
  - score: 10
    time: 1s
    memory: 1024m
    cases:
      - input: 1.in
        output: 1.out
  - score: 90
    time: 1s
    memory: 1024m
    cases:
      - input: 1.in
        output: 1.out
      - input: 2.in
        output: 2.out
```
Does the judger evaluate 1.in twice? or only once?

**Comment by undefined-moe** [comment]
twice.

**Comment by junukwon7** [comment]
> twice.

My suggestion was that it could be once.

**Comment by undefined-moe** [comment]
what about something like this?

```yaml
subtasks:
  - score: 30
    time: 1s
    memory: 64m
    cases:
      - input: a.in
        output: a.out
      - input: b.in
        output: b.out
  - score: 30
    time: 0.5s
    memory: 32m
    cases:
      - input: c.in
        output: c.out
      - input: d.in
        output: d.out
  - score: 40
    if: [0, 1]
    time: 0.5s
    memory: 32m
    cases:
      - input: e.in
        output: f.out
```
