### ISSUE TITLE
System Error，判题错误

### ISSUE THREAD

**Issue by HaorongX** [hydro-dev/Hydro#363]
日志：
```
[E]  judge  Error: Sandbox Error
        at run (/root/Hydro/packages/hydrojudge/src/sandbox.ts:207:11)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async compile (/root/Hydro/packages/hydrojudge/src/compile.ts:50:9)
        at async Promise.all (index 0)
        at async Object.judge (/root/Hydro/packages/hydrojudge/src/judge/default.ts:207:32)
        at async JudgeTask.doSubmission (/root/Hydro/packages/hydrojudge/src/hosts/hydro.ts:152:5)
        at async JudgeTask.handle (/root/Hydro/packages/hydrojudge/src/hosts/hydro.ts:97:7)
[I]  judge  End: status=8 score=0 time=0ms memory=0kb
```

配置文件
```
hosts:
  localhost:
    type: hydro
    server_url: http://localhost:2333/ 
    uname: judge 
    password: ******
    detail: true 
```
![2022-05-22 13-30-22 的屏幕截图](https://user-images.githubusercontent.com/103825064/169680330-1f9449d7-3883-4377-aeba-d915534035ed.png)

已经安装hydrojudge，作为附加组建启动，没有禁用内置评测机。
