### ISSUE TITLE
Golang compile error : failed to initialize build cache at /w /.cache/go-build: mkdir /w : read-only file system

### ISSUE THREAD

**Issue by Necho-dev** [hydro-dev/Hydro#399]
I'm sorry, there was a little problem when I was configuring the evaluation machine.
There are no exceptions when installing a compiler for the Go language.
```bash
sudo apt-get install golang
```
Restart the sandbox.
```bash
pm2 restart hydro-sandbox
```
Everything is fine in the local ssh.
- foo.go
```go
package main
import "fmt"
func main() {
    var a, b int
    fmt.Scanf("%d%d", &a, &b)
    fmt.Printf("%d\n", a + b)
}
```
```bash
/usr/bin/go build -o foo foo.go
./foo
```
- result
```bash
1 2
3
```
However, an exception occurred while submitting the evaluation using the go language.
```bash
Compile Error 0ms 0KiB
failed to initialize build cache at /w
/.cache/go-build: mkdir /w
: read-only file system
```
I repeatedly reinstalled the Go language compiler and restarted the service, but I couldn't solve it. Please give me some advice.

**Comment by undefined-moe** [comment]
try GOPATH and GOROOT environment variable.

**Comment by Necho-dev** [comment]
> try GOPATH and GOROOT environment variable.

It doesn't seem to work. 
May I have a look at your `go env`

**Comment by undefined-moe** [comment]
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/w/.cache/go-build"
GOENV="/w/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/w/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build133473572=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by Necho-dev** [comment]
> 

Thank you! 
However, I set up the same go env as you, and restarting all the services still didn't solve the problem. 
The same problem occurred on both servers. Can there be a detailed tutorial about  go?

**Comment by undefined-moe** [comment]
I'm not familiar with golang compiler, but rootfs built with nix just works.

```nix
{ pkgs ? import <nixpkgs> { system = "x86_64-linux"; } }:

pkgs.buildEnv {
  name = "judge";
  paths = [
    pkgs.busybox
    pkgs.gcc
    pkgs.go
  ];
  pathsToLink = [ "/bin" ];
}
```

compile command: `/bin/go build -o foo foo.go`

mount.yaml:

```yaml
mount:
  - type: bind
    source: /path/to/result/bin
    target: /bin
    readonly: true
  - type: bind
    source: /nix
    target: /nix
    readonly: true
  - type: bind
    source: /dev/null
    target: /dev/null
  - type: bind
    source: /dev/urandom
    target: /dev/urandom
  - type: bind
    source: /dev/random
    target: /dev/random
  - type: bind
    source: /dev/zero
    target: /dev/zero
  - type: bind
    source: /dev/full
    target: /dev/full
  - type: tmpfs
    target: /w
    data: size=128m,nr_inodes=4k
  - type: tmpfs
    target: /tmp
    data: size=128m,nr_inodes=4k
# (other configuration)
```
