### ISSUE TITLE
自定义编译脚本，群体编译时报错，独立编译不报错

### ISSUE THREAD

**Issue by Taiga-A** [hydro-dev/Hydro#586]
## 背景
写的交互器修改后整题重测，发现全部CE ，手动点击某个提交的重测不会出现此问题， 手动点击多个提交也会 CE。

## 测评设置

config.yaml （部分，去除测试样例）
```yaml
type: interactive
interactor: sj.cc.cc17o2
user_extra_files:
- compile.sh
- template.cc
```

template.cc
```c++
__attribute((constructor)) void before_main() {
  setbuf(stdout, NULL);
}
```

compile.sh （部分，以c++17为例）
```shell
set -e
if [[ $HYDRO_LANG = "cc.cc17" ]] then
  cat template.cc >> foo.cc
  g++ -x c++ foo.cc -o foo -lm -fno-stack-limit -fdiagnostics-color=always -std=c++17 -I/include
fi
```
**注：** `template.cc` 是为了取消输出缓冲区
