### ISSUE TITLE
[BUG] `hydrooj.homepage` 中将 key 设置为 `false` 不起作用

### ISSUE THREAD

**Issue by HeRaNO** [hydro-dev/Hydro#943]
`hydrooj.homepage.yaml` 设置为：

```yaml
- width: 9
  bulletin: true
  contest: 5
  homework: 10
  training: 10
  ranking: 10
  discussion: 20
- width: 3
  hitokoto: false
  starred_problems: 50
  recent_problems: 10
  discussion_nodes: false
  suggestion: true
```

的话，保存配置后主页仍然显示一言和讨论节点，如果修改为：

```yaml
- width: 9
  bulletin: true
  contest: 5
  homework: 10
  training: 10
  ranking: 10
  discussion: 20
- width: 3
  starred_problems: 50
  recent_problems: 10
  suggestion: true
```

就不会显示了。

Bug 出现在 https://github.com/hydro-dev/Hydro/blob/ae24d3952ff1aa1439da636910d00e45864d5974/packages/hydrooj/src/handler/home.ts#L146-L169

函数并未检查 key 对应的 value
